# Generated by Django 3.0.5 on 2024-03-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quotes', models.TextField(default='')),
                ('excert', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now=True)),
                ('pic1', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('pic2', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('pic3', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('video', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Done')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Newslater',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
                ('quotes', models.TextField(default='')),
                ('excert', models.TextField(default='')),
                ('tags', models.TextField(default='')),
                ('pic', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('pic1', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('pic2', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('pic3', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.PositiveIntegerField(default=0)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.BloodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('addressline1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('addressline2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('addressline3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('disease', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('doctor', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.BloodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('addressline1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('addressline2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('addressline3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('disease', models.CharField(blank=True, default='Nothing', max_length=100, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.BloodGroup')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(default='Nothing', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('ondate', models.DateField()),
                ('ontime', models.TimeField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Donor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Locations')),
            ],
        ),
    ]
