# Generated by Django 3.0.5 on 2024-03-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='fullname',
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
