# Generated by Django 3.0.5 on 2024-03-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20240301_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='tags',
            new_name='tag1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='services',
            name='tag2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag6',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag7',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='tag8',
            field=models.TextField(default=''),
        ),
    ]
