# Generated by Django 3.0.5 on 2024-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20240302_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='tag2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag4',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag5',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag6',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag7',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag8',
            field=models.TextField(blank=True, default=''),
        ),
    ]
