# Generated by Django 3.0.5 on 2024-03-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20240303_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='disease',
            new_name='reason',
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('ondate', models.DateField()),
                ('ontime', models.TimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Patient')),
            ],
        ),
    ]
