# Generated by Django 3.0.5 on 2024-03-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20240304_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='doctor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
