# Generated by Django 3.0.5 on 2024-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_bloodrequest_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('occupasion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('stars', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
