# Generated by Django 3.0.5 on 2024-03-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
