# Generated by Django 3.0.5 on 2024-04-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20240305_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blooddonate',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Done')], default=1),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Done')], default=1),
        ),
    ]
