# Generated by Django 3.0.5 on 2024-04-09 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20240405_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organname', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(default='Nothing', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('bloodgroup', models.CharField(max_length=10)),
                ('organ', models.CharField(max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Done')], default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('ondate', models.DateField()),
                ('ontime', models.TimeField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Donor')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Locations')),
            ],
        ),
    ]
