# Generated by Django 3.0.5 on 2024-04-09 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_auto_20240409_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='organstock',
            name='organname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Organ'),
        ),
    ]
