# Generated by Django 3.0.5 on 2024-04-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20240409_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='organdonate',
            name='Report',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='organdonate',
            name='donorstatus',
            field=models.IntegerField(choices=[(1, 'Alive'), (2, 'Death')], default=1),
        ),
        migrations.AlterField(
            model_name='organdonate',
            name='bloodgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Stock'),
        ),
        migrations.AlterField(
            model_name='organdonate',
            name='organ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Organ'),
        ),
    ]
