# Generated by Django 3.0.5 on 2024-04-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_auto_20240409_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('doctor', models.CharField(default='', max_length=100)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Approved'), (3, 'Rejected'), (4, 'Done')], default=1)),
                ('date', models.DateTimeField(auto_now=True)),
                ('ondate', models.DateField()),
                ('ontime', models.TimeField()),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Organ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Patient')),
            ],
        ),
    ]
