# Generated by Django 3.0.5 on 2024-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_organrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
