# Generated by Django 3.0.5 on 2024-04-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_donor_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='coins',
            new_name='rewards',
        ),
    ]
