# Generated by Django 3.0.5 on 2024-04-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_auto_20240422_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='rewards',
            new_name='currency',
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('details', models.TextField()),
                ('terms', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'Claim Now'), (2, 'Claimed'), (3, 'Expired')], default=1)),
                ('banner', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('logo', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('aboutcompany', models.TextField()),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Donor')),
            ],
        ),
    ]
