# Generated by Django 3.0.5 on 2024-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_auto_20240422_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('currency', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, default=None, null=True)),
                ('terms', models.TextField(blank=True, default=None, null=True)),
                ('banner', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('logo', models.FileField(blank=True, default='noimage.jpg', null=True, upload_to='images')),
                ('aboutcompany', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='aboutcompany',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='company',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='details',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='rewards',
            name='title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic1',
            field=models.FileField(blank=True, default='default1.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic2',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pic3',
            field=models.FileField(blank=True, default='default2.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, default='video.webm', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='pic',
            field=models.FileField(blank=True, default='default8.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='pic',
            field=models.FileField(blank=True, default='default8.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='pic',
            field=models.FileField(blank=True, default='default5.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='pic1',
            field=models.FileField(blank=True, default='noimage6.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='pic2',
            field=models.FileField(blank=True, default='noimage7.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='services',
            name='pic3',
            field=models.FileField(blank=True, default='noimage4.jpg', null=True, upload_to='images'),
        ),
    ]
