# Generated by Django 3.0.5 on 2024-04-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_auto_20240422_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewards',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
