# Generated by Django 3.0.5 on 2024-04-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_auto_20240423_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='web',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='web',
        ),
    ]
