# Generated by Django 3.0.5 on 2024-04-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_auto_20240423_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tag1', models.TextField(blank=True, default='')),
                ('tag2', models.TextField(blank=True, default='')),
                ('tag3', models.TextField(blank=True, default='')),
                ('tag4', models.TextField(blank=True, default='')),
                ('social1', models.TextField(blank=True, default='')),
                ('social2', models.TextField(blank=True, default='')),
                ('social3', models.TextField(blank=True, default='')),
                ('social4', models.TextField(blank=True, default='')),
                ('pic', models.FileField(blank=True, default='default8.jpg', null=True, upload_to='images')),
            ],
        ),
    ]
