# Generated by Django 3.0.5 on 2024-04-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.IntegerField(choices=[(1, 'left'), (2, 'right')], default=1),
        ),
    ]
