# Generated by Django 3.0.5 on 2024-04-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Upcoming'), (2, 'Latest')], default=1),
        ),
    ]
