# Generated by Django 3.0.5 on 2024-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0033_blog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='eventdate',
            field=models.DateField(blank=True, default='2024-04-01', null=True),
        ),
    ]
