# Generated by Django 3.0.5 on 2024-04-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_blog_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
    ]
