# Generated by Django 3.0.5 on 2024-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0035_blog_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='place',
            field=models.CharField(default='Dehradun', max_length=100),
        ),
    ]
