# Generated by Django 4.1.2 on 2024-04-28 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0036_auto_20240425_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organstock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Withdrawn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('upi', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'Done')], default=1)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.donor')),
            ],
        ),
    ]
